apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-api-dev-config
  labels:
    app.kubernetes.io/name: mimir-api
    app.kubernetes.io/instance: dev
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_HTTP_PORTS: "5000"
  Jwt__Audience: mimir-api
  Jwt__Authority: http://mimir-keycloak.dev.svc.cluster.local:8080/realms/mimir
  Jwt__RequireHttpsMetadata: "false"
  RabbitMQ__Host: mimir-rabbitmq.dev.svc.cluster.local
  RabbitMQ__Port: "5672"
  RabbitMQ__User: guest
  LiteLLM__BaseUrl: http://mimir-litellm.dev.svc.cluster.local:4000
  Cors__AllowedOrigins: '["http://localhost:3000"]'
