apiVersion: v1
kind: Service
metadata:
  name: mimir-api-dev
  labels:
    app.kubernetes.io/name: mimir-api
    app.kubernetes.io/instance: dev
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mimir-api
    app.kubernetes.io/instance: dev
  ports:
    - name: http
      port: 80
      targetPort: http
