apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ include "nem-mimir.fullname" . }}'
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    helm.sh/chart: '{{ include "nem-mimir.chart" . }}'
    app.kubernetes.io/name: '{{ include "nem-mimir.name" . }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: '{{ include "nem-mimir.name" . }}'
      app.kubernetes.io/instance: '{{ .Release.Name }}'
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/externalsecret.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: '{{ include "nem-mimir.name" . }}'
        app.kubernetes.io/instance: '{{ .Release.Name }}'
    spec:
      serviceAccountName: '{{ include "nem-mimir.serviceAccountName" . }}'
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      securityContext:
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
      containers:
        - name: nem-mimir
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: '{{ include "nem-mimir.fullname" . }}'
            - secretRef:
                name: '{{ .Values.openbao.targetSecretName }}'
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
          securityContext:
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
            runAsUser: {{ .Values.securityContext.runAsUser }}
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
            capabilities:
              drop:
                - ALL
