apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: '{{ include "nem-mimir.fullname" . }}-openbao'
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    helm.sh/chart: '{{ include "nem-mimir.chart" . }}'
    app.kubernetes.io/name: '{{ include "nem-mimir.name" . }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
spec:
  refreshInterval: {{ .Values.openbao.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.openbao.clusterSecretStore }}
  target:
    name: {{ .Values.openbao.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: ConnectionStrings__DefaultConnection
      remoteRef:
        key: {{ .Values.openbao.secretPathPrefix }}
        property: {{ .Values.openbao.keys.databaseConnectionString }}
    - secretKey: Database__ConnectionString
      remoteRef:
        key: {{ .Values.openbao.secretPathPrefix }}
        property: {{ .Values.openbao.keys.databaseConnectionString }}
    - secretKey: LiteLlm__ApiKey
      remoteRef:
        key: {{ .Values.openbao.secretPathPrefix }}
        property: {{ .Values.openbao.keys.liteLlmApiKey }}
    - secretKey: RabbitMQ__ConnectionString
      remoteRef:
        key: {{ .Values.openbao.secretPathPrefix }}
        property: {{ .Values.openbao.keys.rabbitMqConnectionString }}
