apiVersion: v1
kind: Secret
metadata:
  name: mimir-api-staging-secrets
  labels:
    app.kubernetes.io/name: mimir-api
    app.kubernetes.io/instance: staging
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: REPLACE_ME
  RabbitMQ__Password: REPLACE_ME
  Keycloak__ClientSecret: REPLACE_ME
  LiteLLM__ApiKey: REPLACE_ME
